export const MAX_ORCHESTRATION_AGENTS = 20;
export const MAX_ORCHESTRATION_PARALLEL = 20;
export const MAX_SUBAGENT_DELEGATION_DEPTH = 3;
export const MAX_SUBAGENT_DELEGATIONS_PER_TASK = 10;
export const MAX_SUBAGENT_DELEGATE_PARALLEL = 10;
